# Project information
site_name: Casette's Notebook
site_description: Casette's Notebook
site_author: Casette
site_url: https://miraitowaves.github.io/


# Repository
repo_name: 'miraitowaves/miraitowaves.github.io'
repo_url: 'https://github.com/miraitowaves/miraitowaves.github.io'


# Copyright
copyright: "Copyright &copy; 2024 - 2024 Casette"


theme:
  name: material
  palette:
    primary: 'light green'
    accent: 'light green'

  feature:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top

  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
  
  logo: 'images/logo.svg'
  favicon: 'assets/images/favicon.png'

  language: 'zh'


# # Customization
# extra:
#   social:
#     - type: github
#       link: https://github.com/miraitowaves

#   search:
#     language: 'ja'

#   disqus: 'miraitowaves'


# # Extensions
# markdown_extensions:
#   - admonition
#   - codehilite:
#       guess_lang: false
#       linenums: false
#   - toc:
#       permalink: true
#   - footnotes
#   - meta
#   - def_list
#   - pymdownx.arithmatex
#   - pymdownx.betterem:
#       smart_enable: all
#   - pymdownx.caret
#   - pymdownx.critic
#   - pymdownx.details
#   - pymdownx.emoji:
#       emoji_generator: !!python/name:pymdownx.emoji.to_png
#   - pymdownx.inlinehilite
#   - pymdownx.magiclink
#   - pymdownx.mark
#   - pymdownx.smartsymbols
#   - pymdownx.superfences
#   - pymdownx.tasklist
#   - pymdownx.tilde

# extra_javascript:
#   - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'


# # Google Analytics
# google_analytics:
#   - "UA-156919721-1"
#   - "auto"


# edit_uri:

# plugins:
#   - search

nav:
  - Home:
    - index.md
    - 更新记录: changelog.md
    - 友链: link.md
  - Computer Science:
    - 数据结构与算法: 
      - ds/index.md
      - 算法分析: ds/algorithm.md
      - 树: ds/tree.md
      - 堆: ds/heap.md
      - 并查集: ds/set.md
      - 图论: ds/graph.md
      - 排序: ds/sort.md
      - 散列: ds/hash.md
    - 高级数据结构与算法分析:
      - ADS/index.md
    - 图像信息处理:
      - dip/index.md
      - 图像信息处理介绍: dip/dip1.md
      - 二值图像和形态学: dip/dip2.md
      - 图像灰度变换与直方图: dip/dip3.md
      - 几何变换: dip/dip5.md
      - 卷积与滤波: dip/dip6.md
      - 双边滤波的加速: dip/dip7.md
      - 引导滤波: dip/dip8.md
      - 稀疏范数滤波: dip/dip9.md
      - 傅里叶变换: dip/dip10.md
      - 图像特征检测和提取: dip/dip11.md
      - 深度学习: dip/dip12.md
    - 面向对象程序设计: 
      - OOP/index.md
      - Introduction: OOP/oop1.md
      - Class: OOP/oop2.md
      - Container: OOP/oop3.md
      - Function: OOP/oop4.md
      - Constant and Static: OOP/oop5.md
      - Inheritance: OOP/oop6.md
      - Polymorphism: OOP/oop7.md
      - Copy Ctor: OOP/oop8.md
      - Overloaded Operators: OOP/oop9.md
      - Templates: OOP/oop10.md
      - Exception: OOP/oop11.md
      - Smart Pointers: OOP/oop12.md
    - 量子计算理论与软件系统: 
      - Quan/index.md
      - 量子态与量子门: Quan/chap1.md
      - 量子测量: Quan/chap2.md
      # - 量子算法: Quan/chap3.md
    - 计算理论:
      - TCS/index.md
    - 应用运筹学基础:
      - AOR/index.md
  - System: 
    - 计算机系统概论: 
      - ICS/index.md
      - Introduction: ICS/ICS-1.md
      - Bits, Data Types and Operations: ICS/ICS-2.md
      - Digital Logic Structures: ICS/ICS-3.md
      - The von Neumann Model: ICS/ICS-4.md
      - LC-3: ICS/ICS-5.md
      - Programming: ICS/ICS-6.md
      - Assembly Language: ICS/ICS-7.md
      - Data Structures: ICS/ICS-8.md
      - I/0: ICS/ICS-9.md
    - CSAPP:
      - 优化程序性能: CSAPP/5.md
      - 存储器层次结构: CSAPP/6.md
      - 链接: CSAPP/7.md
      - 异常控制流: CSAPP/8.md
      - 虚拟内存: CSAPP/9.md
    - 计算机逻辑设计基础: 
      - Logic/index.md
      - 数字系统和信息: Logic/logic01.md
      - 组合逻辑电路: Logic/logic02.md
      - 组合逻辑电路设计: Logic/logic03.md
      - 时序逻辑电路: Logic/logic04.md
      - 寄存器与寄存器传输: Logic/logic06.md
      - 数字硬件设计: Logic/logic05.md
      - 内存基础: Logic/logic07.md
    - 数据库系统:
      - DB/index.md
      - 数据库介绍: DB/db1.md
      - 关系模型: DB/db2.md
      - SQL 语言介绍: DB/db3.md
      - 中级 SQL: DB/db4.md
      - 高级 SQL: DB/db5.md
      - 实体-关系模型: DB/db6.md
      - 关系数据库设计: DB/db7.md
      - 物理存储系统: DB/db8.md
      - 数据存储结构: DB/db9.md
      - 索引: DB/db10.md
      - 查询处理: DB/db11.md
      - 查询优化: DB/db12.md
      - 事务: DB/db13.md
      - 并发控制: DB/db14.md 
      - 故障恢复: DB/db15.md
    - 计算机组成与设计:
      - CO/index.md
      - 计算机概要与技术: CO/co1.md
      - 计算机的算术运算: CO/co3.md
      - 指令：计算机的语言: CO/co2.md
      - 处理器: CO/co4.md
      - 内存层次架构: CO/co5.md
      - 存储和 IO: CO/co6.md
    - 计算机体系结构:
      - CA/index.md
      - 计算机设计基础: CA/CA1.md
      - 流水线: CA/CA2.md
      - 内存层次: CA/CA3.md
      - 指令级并行: CA/CA4.md
      - DLP 和 TLP: CA/CA5.md
    - 操作系统原理与实践:
      - OS/index.md
      - OS 结构: OS/chap01.md
      - 进程: OS/chap02.md
      - 进程间通信: OS/chap03.md
      - 线程: OS/chap04.md
      - 调度: OS/chap05.md
      - 同步: OS/chap06.md
      - 死锁: OS/chap07.md
      - 主存: OS/chap08.md
      - 虚拟内存: OS/chap09.md
      - 大容量存储: OS/chap10.md
      - I/O 系统: OS/chap11.md
      - 文件系统接口: OS/chap12.md
      - 文件系统实现: OS/chap13.md
    - 编译原理:
      - Compiler/index.md
      - 介绍: Compiler/lec1.md
      - 词法分析: Compiler/lec2.md
      - 语法分析: Compiler/lec3.md
  - AI:
    - Deep Learning: 
      - DL/index.md
      - 图像分类: DL/lec01.md
      - 线性分类器: DL/lec02.md
      - 优化: DL/lec03.md
      - 神经网络: DL/lec04.md
      - 反向传播: DL/lec05.md
      - 卷积神经网络: DL/lec06.md
      - CNN 架构: DL/lec07.md
    - Efficient ML:
      - TinyML/index.md
      - 剪枝与稀疏性: TinyML/pruning.md
      - 量化: TinyML/quantization.md
      - Transformer & LLM: TinyML/llm.md
  - Mathematics:
    - 线性代数: 
      - 线性代数Ⅱ(H): Mathematics/线性代数Ⅱ(H)/Rings.md
    - 数据建模与分析:
      - 读书报告: MLT/report.md
      - 感知机: MLT/mlt2.md
  - Papers:
    - Paper/index.md
    - BiS-KM: Paper/BiS-KM.md
    - ZeRO: Paper/ZeRO.md
    - Megatron-LM: Paper/Megatron-LM.md
    - GPipe: Paper/GPipe.md
    - 混合精度训练: Paper/mixed_precision.md
    - FAST: Paper/FAST.md
    - Softmax 加速: Paper/softmax.md
  - Miscellaneous:
    - Misc/index.md
    - 浮点数与定点数: Misc/float.md
    - FPGA Programming: Misc/fpga.md
    - LLVM:
      - LLVM IR: Misc/LLVM/ir.md
    - CGRA:
      - CGRA 介绍: Misc/CGRA/intro.md
    - Android:
      - 触控事件的数据流: android/dataflow.md